# Generated by Django 4.2.30 on 2026-10-04 02:35

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('game_type', models.CharField(choices=[('BACCARAT', 'Baccarat (Punto Banco)'), ('CRASH', 'Cross Chicken (Crash)')], max_length=20)),
                ('server_seed', models.CharField(max_length=128)),
                ('server_seed_hash', models.CharField(max_length=128)),
                ('client_seed', models.CharField(default='toqi999bigwin', max_length=64)),
                ('nonce', models.PositiveIntegerField(default=1)),
                ('crash_point', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('outcome_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending / Betting Open'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bet_choice', models.CharField(max_length=50)),
                ('auto_cashout', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cashed_out_at', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('CASHED_OUT', 'Cashed Out'), ('PUSH', 'Pushed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='games.gameround')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
